import {
  lightTemplate,
  darkTemplate,
  deuteranopiaTemplate,
  tritanopiaTemplate,
  junoTemplate,
  royalTemplate,
  electricblueTemplate,
  pineTemplate,
  revolutionTemplate,
  yellowTemplate,
  taupeTemplate,
  // lightTheme,
  // darkTheme,
  // deuteranopiaTheme,
} from './theme';

export {
  lightTemplate,
  darkTemplate,
  deuteranopiaTemplate,
  tritanopiaTemplate,
  junoTemplate,
  royalTemplate,
  electricblueTemplate,
  pineTemplate,
  revolutionTemplate,
  yellowTemplate,
  taupeTemplate,
  // lightTheme,
  // darkTheme,
  // deuteranopiaTheme,
};
